name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: Build with Xcode
      run: |
              export PATH="./node_modules/.bin:$PATH"
              xcodebuild -workspace Freetime.xcworkspace -scheme Freetime-AppCenter CODE_SIGNING_ALLOWED="NO"
